import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const depixel = localFont({
	src: "./fonts/depixelbreit.woff",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${depixel.className} bg-black text-white tracking-[0.2rem]`}
			>
				{children}
			</body>
		</html>
	);
}
